/**
 * MIDI CC (Control Change) reference table
 * Maps CC numbers to their official names and friendly display names
 */
export const MIDI_CC_REFERENCE: Record<number, { type: string; name: string }> = {
	0: { type: "bankselectcoarse", name: "Bank Select (Coarse)" },
	1: { type: "modulationwheelcoarse", name: "Modulation Wheel" },
	2: { type: "breathcontrollercoarse", name: "Breath Controller" },
	3: { type: "controller3", name: "Controller 3" },
	4: { type: "footcontrollercoarse", name: "Foot Controller" },
	5: { type: "portamentotimecoarse", name: "Portamento Time" },
	6: { type: "dataentrycoarse", name: "Data Entry (Coarse)" },
	7: { type: "volumecoarse", name: "Channel Volume" },
	8: { type: "balancecoarse", name: "Balance" },
	9: { type: "controller9", name: "Controller 9" },
	10: { type: "pancoarse", name: "Pan" },
	11: { type: "expressioncoarse", name: "Expression" },
	12: { type: "effectcontrol1coarse", name: "Effect Control 1" },
	13: { type: "effectcontrol2coarse", name: "Effect Control 2" },
	14: { type: "controller14", name: "Controller 14" },
	15: { type: "controller15", name: "Controller 15" },
	16: { type: "generalpurposeslider1", name: "General Purpose Slider 1" },
	17: { type: "generalpurposeslider2", name: "General Purpose Slider 2" },
	18: { type: "generalpurposeslider3", name: "General Purpose Slider 3" },
	19: { type: "generalpurposeslider4", name: "General Purpose Slider 4" },
	20: { type: "controller20", name: "Controller 20" },
	21: { type: "controller21", name: "Controller 21" },
	22: { type: "controller22", name: "Controller 22" },
	23: { type: "controller23", name: "Controller 23" },
	24: { type: "controller24", name: "Controller 24" },
	25: { type: "controller25", name: "Controller 25" },
	26: { type: "controller26", name: "Controller 26" },
	27: { type: "controller27", name: "Controller 27" },
	28: { type: "controller28", name: "Controller 28" },
	29: { type: "controller29", name: "Controller 29" },
	30: { type: "controller30", name: "Controller 30" },
	31: { type: "controller31", name: "Controller 31" },
	32: { type: "bankselectfine", name: "Bank Select (Fine)" },
	33: { type: "modulationwheelfine", name: "Modulation Wheel (Fine)" },
	34: { type: "breathcontrollerfine", name: "Breath Controller (Fine)" },
	35: { type: "controller35", name: "Controller 35" },
	36: { type: "footcontrollerfine", name: "Foot Controller (Fine)" },
	37: { type: "portamentotimefine", name: "Portamento Time (Fine)" },
	38: { type: "dataentryfine", name: "Data Entry (Fine)" },
	39: { type: "volumefine", name: "Channel Volume (Fine)" },
	40: { type: "balancefine", name: "Balance (Fine)" },
	41: { type: "controller41", name: "Controller 41" },
	42: { type: "panfine", name: "Pan (Fine)" },
	43: { type: "expressionfine", name: "Expression (Fine)" },
	44: { type: "effectcontrol1fine", name: "Effect Control 1 (Fine)" },
	45: { type: "effectcontrol2fine", name: "Effect Control 2 (Fine)" },
	46: { type: "controller46", name: "Controller 46" },
	47: { type: "controller47", name: "Controller 47" },
	48: { type: "controller48", name: "Controller 48" },
	49: { type: "controller49", name: "Controller 49" },
	50: { type: "controller50", name: "Controller 50" },
	51: { type: "controller51", name: "Controller 51" },
	52: { type: "controller52", name: "Controller 52" },
	53: { type: "controller53", name: "Controller 53" },
	54: { type: "controller54", name: "Controller 54" },
	55: { type: "controller55", name: "Controller 55" },
	56: { type: "controller56", name: "Controller 56" },
	57: { type: "controller57", name: "Controller 57" },
	58: { type: "controller58", name: "Controller 58" },
	59: { type: "controller59", name: "Controller 59" },
	60: { type: "controller60", name: "Controller 60" },
	61: { type: "controller61", name: "Controller 61" },
	62: { type: "controller62", name: "Controller 62" },
	63: { type: "controller63", name: "Controller 63" },
	64: { type: "holdpedal", name: "Hold Pedal (Sustain)" },
	65: { type: "portamento", name: "Portamento" },
	66: { type: "sustenutopedal", name: "Sustenuto Pedal" },
	67: { type: "softpedal", name: "Soft Pedal" },
	68: { type: "legatopedal", name: "Legato Pedal" },
	69: { type: "hold2pedal", name: "Hold 2 Pedal" },
	70: { type: "soundvariation", name: "Sound Variation" },
	71: { type: "resonance", name: "Resonance" },
	72: { type: "soundreleasetime", name: "Sound Release Time" },
	73: { type: "soundattacktime", name: "Sound Attack Time" },
	74: { type: "brightness", name: "Brightness" },
	75: { type: "soundcontrol6", name: "Sound Control 6" },
	76: { type: "soundcontrol7", name: "Sound Control 7" },
	77: { type: "soundcontrol8", name: "Sound Control 8" },
	78: { type: "soundcontrol9", name: "Sound Control 9" },
	79: { type: "soundcontrol10", name: "Sound Control 10" },
	80: { type: "generalpurposebutton1", name: "General Purpose Button 1" },
	81: { type: "generalpurposebutton2", name: "General Purpose Button 2" },
	82: { type: "generalpurposebutton3", name: "General Purpose Button 3" },
	83: { type: "generalpurposebutton4", name: "General Purpose Button 4" },
	84: { type: "controller84", name: "Controller 84" },
	85: { type: "controller85", name: "Controller 85" },
	86: { type: "controller86", name: "Controller 86" },
	87: { type: "controller87", name: "Controller 87" },
	88: { type: "controller88", name: "Controller 88" },
	89: { type: "controller89", name: "Controller 89" },
	90: { type: "controller90", name: "Controller 90" },
	91: { type: "reverblevel", name: "Reverb Level" },
	92: { type: "tremololevel", name: "Tremolo Level" },
	93: { type: "choruslevel", name: "Chorus Level" },
	94: { type: "celestelevel", name: "Celeste Level" },
	95: { type: "phaserlevel", name: "Phaser Level" },
	96: { type: "databuttonincrement", name: "Data Button Increment" },
	97: { type: "databuttondecrement", name: "Data Button Decrement" },
	98: { type: "nonregisteredparametercoarse", name: "Non-Registered Parameter (Coarse)" },
	99: { type: "nonregisteredparameterfine", name: "Non-Registered Parameter (Fine)" },
	100: { type: "registeredparametercoarse", name: "Registered Parameter (Coarse)" },
	101: { type: "registeredparameterfine", name: "Registered Parameter (Fine)" },
	102: { type: "controller102", name: "Controller 102" },
	103: { type: "controller103", name: "Controller 103" },
	104: { type: "controller104", name: "Controller 104" },
	105: { type: "controller105", name: "Controller 105" },
	106: { type: "controller106", name: "Controller 106" },
	107: { type: "controller107", name: "Controller 107" },
	108: { type: "controller108", name: "Controller 108" },
	109: { type: "controller109", name: "Controller 109" },
	110: { type: "controller110", name: "Controller 110" },
	111: { type: "controller111", name: "Controller 111" },
	112: { type: "controller112", name: "Controller 112" },
	113: { type: "controller113", name: "Controller 113" },
	114: { type: "controller114", name: "Controller 114" },
	115: { type: "controller115", name: "Controller 115" },
	116: { type: "controller116", name: "Controller 116" },
	117: { type: "controller117", name: "Controller 117" },
	118: { type: "controller118", name: "Controller 118" },
	119: { type: "controller119", name: "Controller 119" },
	120: { type: "allsoundoff", name: "All Sound Off" },
	121: { type: "resetallcontrollers", name: "Reset All Controllers" },
	122: { type: "localcontrol", name: "Local Control" },
	123: { type: "allnotesoff", name: "All Notes Off" },
	124: { type: "omnimodeoff", name: "Omni Mode Off" },
	125: { type: "omnimodeon", name: "Omni Mode On" },
	126: { type: "monomodeon", name: "Mono Mode On" },
	127: { type: "polymodeon", name: "Poly Mode On" },
}